const recipes = [
  {
    id: '1',
    name: 'Knäckebröd med avokado & ägg',
    image: '/frukost/ID-1.png',
    ingredients: ['2 knäckebröd', '1 avokado', '2 kokta ägg', 'salt', 'peppar'],
    instructions: ['Bre avokado på knäckebröd.', 'Lägg på äggskivor.'],
    nutrition: { Calories: '500 kcal', Protein: '30g', Carbs: '40g', Fat: '25g' },
    cookTime: '5 min',
    difficulty: 3,
    category:"Frukost",
    description: "Knäckebröd med avokado & ägg",
    protein: "Vegetarisk",
    rating: 5,
  },
  {
    id: '2',
    name: 'Youghurt med granola & banan',
    image: '/frukost/ID-2.png',
    ingredients: ['200 g laktosfri yoghurt', '80 g granola', '1 banan', 'kanel'],
    instructions: ['Häll yoghurt i skål.', 'Toppa med granola och banan.'],
    nutrition: { Calories: '500 kcal', Protein: '30g', Carbs: '40g', Fat: '25g' },
    cookTime: '3 min',
    difficulty: 1,
    category:"Frukost",
    description: "Youghurt med granola & banan",
    protein: "Vegetarisk",
    rating: 3
  },
  {
    id: '3',
    name: 'Fullkornsbröd med pålägg',
    image: '/frukost/ID-3.png',
    ingredients: ['4 skivor fullkornsbröd', '4 kycklingpålägg', 'gurka', 'tomat'],
    instructions: ['Grilla bröd.', 'Lägg på pålägg och grönsaker.'],
    nutrition: { Calories: '500 kcal', Protein: '30g', Carbs: '40g', Fat: '25g' },
    cookTime: '10 min',
    difficulty: 1,
    category:"Frukost",
    description: "Fullkornsbröd med pålägg",
    protein: "Vegetarisk",
    rating: 3
  },
  {
    id: '4',
    name: 'Ägg & bacon med gröt',
    image: '/frukost/ID-4.png',
    ingredients: ['2 ägg', '80 g bacon', '200 g havregrynsgröt', '50 g bär'],
    instructions: ['Stek ägg och bacon.', 'Servera med gröt och bär.'],
    nutrition: { Calories: '500 kcal', Protein: '30g', Carbs: '40g', Fat: '25g' },
    cookTime: '15 min',
    difficulty: 1,
    category:"Frukost",
    description: "Ägg & bacon med gröt",
    protein: "Bacon",
    rating: 4
  },
   {
    id: '100',
    name: 'Kyckling i gräddsås med zucchini',
    image: '/lunch/ID-100.png',
    ingredients: ['600 g kycklingbröst', '2 dl gräddfil', '2 vitlöksklyftor', '1 gul lök', '3 zucchini', '2 msk olivolja'],
    instructions: ['Fräs kyckling, lök och vitlök i olja.', 'Tillsätt zucchini och gräddfil.',
'Låt sjuda 10 min.',],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '25 min',
    difficulty: 1,
    category:"Lunch",
    description: "Kyckling i gräddsås med zucchini",
    protein: "Kyckling",
    rating: 5
  },
   {
    id: '101',
    name: 'Biff med lök och rödkålssallad',
    image: '/lunch/ID-101.png',
    ingredients: ['600 g biff', '2 lökar', '½ rödkål', '1 msk vinäger', '2 msk olivolja'],
    instructions: ['Stek biff och lök.', 'Blanda rödkål med vinäger och olja.'],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '20 min',
    difficulty: 1,
    category:"Lunch",
    description: "Biff med lök och rödkålssallad",
    protein: "Nöt",
    rating: 3
  },
     {
    id: '102',
    name: 'Fläskkotletter med vitlöksbroccoli',
    image: '/lunch/ID-102.png',
    ingredients: ['6 fläskkotletter', '1 broccoli', '3 vitlöksklyftor', '2 msk smör'],
    instructions: ['Krydda och grilla kotletter.', 'Stek broccoli med vitlök och smör.'],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '30 min',
    difficulty: 2,
    category:"Lunch",
    description: "Fläskkotletter med vitlöksbroccoli",
    protein: "Fläsk",
    rating: 3
  },
    {
    id: '103',
    name: 'Tonfisksallad med avokado',
    image: '/lunch/ID-103.png',
    ingredients: ['3 burkar tonfisk', '3 msk majonnäs', '2 avokador', '6 salladsblad'],
    instructions: ['Blanda tonfisk, majonnäs och avokado.', 'Servera på salladsblad.'],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '10 min',
    difficulty: 1,
    category:"Lunch",
    description: "Tonfisksallad med avokado",
    protein: "Fisk",
    rating: 3
  },
      {
    id: '104',
    name: 'Vitlöksfisk med spenatsallad',
    image: '/lunch/ID-104.png',
    ingredients: ['600 g torsk', '3 vitlöksklyftor', '2 msk smör', '200 g spenat'],
    instructions: ['Stek fisk med vitlök och smör.', 'Blanda spenat med olja.'],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '20 min',
    difficulty: 1,
    category:"Lunch",
    description: "Vitlöksfisk med spenatsallad",
    protein: "Fisk",
    rating: 3
  },
      {
    id: '105',
    name: 'Salladstacos med bacon',
    image: '/lunch/ID-104.png',
    ingredients: ['450 g nötfärs', '1 påseTacokrydda', '90 g bacon', '6 salladsblad', '1 tomat'],
    instructions: ['Stek bacon och färs.', ' Servera i salladsblad med tomat.'],
    nutrition: { Calories: '650 kcal', Protein: '25 g', Carbs: '75 g', Fat: '25 g' },
    cookTime: '15 min',
    difficulty: 1,
    category:"Lunch",
    description: "Salladstacos med bacon",
    protein: "Bacon",
    rating: 3
  },
];